name: data_type_detector
description: "Detect Dart and JSON data types automatically with deep parsing support for primitives, iterables, and nested maps."
version: 1.0.0
repository: https://github.com/Mohiuddin655-PUB/data_type

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
